event_inherited();
idlespr = spr_banana_idle;
stunfallspr = spr_banana_stun;
walkspr = spr_banana_idle;
grabbedspr = spr_banana_stun;
scaredspr = spr_banana_scared;
spr_dead = spr_banana_dead;
usepalette = true;
spr_palette = spr_banana_palette;
sprite_index = walkspr;
sugary = true;
substate = 0;
