init_collision();
countdown = 125;
image_speed = 0.35;
drop = true;
grounded = false;
state = states.normal;
playerid = noone;
pizzagoblin = false;
kickbuffer = 0;
movespeed = 0;
defused = false;
destroy = true;
baddie = false;
hurtplayer = true;
grabbable = true;
bomblit_spr = spr_bomblit;
bouncesound = false;
snd = fmod_event_create_instance("event:/sfx/pep/bombfuse");
