hp = 3;
number = 0;
maxhp = hp;
parentID = noone;
spotID = noone;
blockID = noone;
death = false;
statue = true;
fall = false;
contemplated = false;
hitX = x;
hitY = y;
hitLag = 0;
depth = 50;
init_collision();
grabID = noone;
image_speed = 0;
sprite_index = choose(spr_pepperman_statues1, spr_pepperman_statues2, spr_pepperman_statues3);
