init_collision();
movespeed = 7;
depth = -8;
jumpspeed = 11;
state = states.chase;
rubberband = false;
rubberband_dir = 1;
targetplayer = obj_player1;
targetRoom = room;
targetDoor = "A";
image_speed = 0.35;
LAG_STEPS = 45;
followqueue = ds_queue_create();
startx = obj_player1.x;
starty = obj_player1.y;
