targetRoom = beach_1;
level = "beach";
sprite_index = spr_gate_plage;
bgsprite = spr_gate_plageBG;
title_index = 8;
titlecard_index = 8;
title_music = "event:/music/w3/beachtitle";
group_arr = ["beachgroup"];
msg = "Pineapple Beach";
