image_speed = 0.35;
init_collision();
grav = 0;
dropspotx = 0;
dropspoty = 0;
grab_xstart = x;
grab_ystart = y;
released = false;
grabbing = false;
thumbingup = false;
xstarte = x;
ystarte = y;
delay = 5;
player = noone;
maxaccel = 10;
accel = 0;
depth = -10;
