event_inherited();
usepalette = true;
stunfallspr = spr_gumslime_stun;
walkspr = spr_gumslime_walk;
scaredspr = spr_gumslime_scared;
ragespr = spr_gumslime_rage;
spr_dead = spr_gumslime_dead;
paletteselect = 0;
spr_palette = spr_gumslime_palette;
sprite_index = walkspr;
sugary = true;
