event_inherited();
usepalette = true;
stunfallspr = spr_babybear_stun;
walkspr = spr_babybear_walk;
scaredspr = spr_babybear_scared;
ragespr = spr_babybear_rage;
spr_dead = spr_babybear_dead;
spr_palette = spr_babybear_palette;
usepalette = true;
sprite_index = walkspr;
sugary = true;
