event_inherited();
movespeed = 2;
hitboxcreate = false;
state = states.walk;
image_speed = 0.35;
sign_id = noone;
spr_dead = spr_piraneapple_dead;
alarm[1] = 10;
mask_index = spr_player_mask;
hamspotted = false;
