scr_initenemy();
image_speed = 0.35;
charge = false;
stun = false;
stunned = 0;
init_collision();
movespeed = 0;
hitboxcreate = false;
mask_index = spr_player_mask;
steppy = 20;
flash = false;
depth = 0;
image_xscale = -1;
boundbox = false;
chargebuffer = 0;
