#region enum

enum states
{
	normal,
	revolver,
	dynamite,
	boots,
	grabbed,
	tumble,
	finishingblow,
	ejected,
	transition,
	fireass,
	firemouth,
	mort,
	mortjump,
	mortattack,
	morthook,
	hook,
	ghost,
	ghostpossess,
	titlescreen, // also used as the "do nothing" state
	hookshot,
	tacklecharge,
	cheeseball,
	cheeseballclimbwall,
	slap,
	cheesepep,
	cheesepepstick,
	cheesepepjump,
	cheesepepfling,
	cheesepeplaunch,
	cheesepepstickside,
	cheesepepstickup,
	rideweenie,
	motorcycle,
	boxxedpep,
	boxxedpepspin,
	boxxedpepjump,
	pistolaim,
	climbwall,
	knightpepslopes,
	portal,
	secondjump,
	chainsawbump,
	handstandjump,
	lungeattack,
	lungegrab,
	dashtumble,
	gottreasure,
	knightpep,
	knightpepattack,
	knightpepbump,
	meteorpep,
	bombpep,
	bombgrab,
	bombpepside,
	bombpepup,
	grabbing,
	chainsawpogo,
	shotgunjump,
	pogo,
	stunned,
	highjump,
	chainsaw,
	facestomp,
	mach4, // doesnt exist
	timesup,
	machroll,
	shotgun,
	shotguncrouch,
	shotguncrouchjump,
	shotgunshoot,
	shotgundash,
	shotgunfreefall,
	pistol,
	machfreefall,
	throwing,
	slam,
	superslam,
	skateboard,
	grind,
	grab,
	punch,
	backkick,
	uppunch,
	shoulder,
	backbreaker,
	graffiti,
	bossdefeat,
	pizzathrow,
	bossintro,
	dead, // originally "gameover"
	keyget,
	tackle,
	jump,
	ladder,
	slipnslide,
	comingoutdoor,
	smirk,
	Sjump,
	victory,
	Sjumpprep,
	crouch,
	crouchjump,
	crouchslide,
	mach1,
	mach2,
	machslide,
	bump,
	hurt,
	freefall,
	hang,
	turning, // doesnt exist
	freefallland,
	door,
	barrel,
	barreljump,
	barrelclimbwall,
	barrelslide,
	current,
	boulder,
	taxi,
	runonball,
	mach3,
	freefallprep,
	Sjumpland,
	faceplant,
	rage,
	idle,
	bounce,
	charge,
	pizzagoblinthrow,
	turn,
	hitceiling, // doesnt exist
	hitwall, // doesnt exist
	groundpoundland,
	walk,
	fall,
	land,
	hit,
	stun,
	recovery, // doesnt exist
	stomped, // doesnt exist
	chase,
	spawnenemy,
	arena,
	arenaintro,
	arenaround,
	actor,
	parry,
	golf,
	float,
	tube,
	unused_1, // 151
	policetaxi,
	shoulderbash,
	pummel,
	staggered,
	thrown,
	supershoulderbash,
	superattackstart,
	superattackcharge,
	superattack,
	shoulderturn,
	fistmatch,
	fistmatchend,
	groundpunchstart,
	slipbanan,
	millionpunch,
	skateboardturn,
	bombkick,
	bombpogo,
	jetpackstart,
	jetpack,
	jetpackcancel,
	jetpackspin,
	shield,
	helicopterhat,
	panicjump,
	smokebombstart,
	smokebombcrawl,
	springshoes,
	cardboard,
	cardboardend,
	mockery,
	bombdelete,
	rocket,
	rocketslide,
	gotoplayer,
	trickjump,
	totem,
	underground,
	ridecow,
	ratmount,
	ratmountjump,
	ratmountattack,
	ratmountspit,
	ratmountclimbwall,
	ratmounthurt,
	ratmountgroundpound,
	ratmountbounce,
	unused_2, // 199
	ratmountballoon,
	ratmounttumble,
	ratmountgrind,
	ratmounttrickjump,
	ratmountskid,
	ratgrabbed,
	blockstance,
	balloon,
	debugstate,
	trashjumpprep,
	trashjump,
	trashroll,
	stringfling,
	stringjump,
	stringfall,
	noisejetpack,
	spiderweb,
	robotidle,
	robotintro,
	robotroaming,
	robotchase,
	robotinvestigate,
	robotseeking,
	flushidle,
	flushtransition,
	animatronic,
	pizzaface_moustache,
	pizzaface_mouth,
	pizzaface_eyes,
	pizzaface_nose,
	pizzaface_ram,
	pizzaface_phase2transition,
	pizzahead_look,
	pizzahead_fishing,
	unused_3, // 234
	pizzahead_bombrun,
	pizzahead_npcthrow,
	pizzahead_portraitthrow,
	pizzahead_enguarde,
	pizzahead_sexypicture,
	pizzahead_pullinglevel,
	pizzahead_eat,
	pizzahead_surprisebox,
	pizzahead_spinningrun,
	pizzahead_spinningkick,
	pizzahead_spinningpunch,
	pizzahead_groundpunch,
	pizzahead_bigkick,
	pizzahead_slamhead,
	pizzahead_slamhead2,
	tv_whitenoise,
	tv_expression,
	playersuperattack,
	unused_4, // 253
	jetpackjump,
	unused_5, // 255
	unused_6, // 256
	bee,
	bee_chase,
	ratmountpunch,
	ratmountcrouch,
	ratmountladder,
	supergrab,
	unused_7, // 263
	magnet,
	antigrav,
	secret,
	contemplate,
	mini,
	reloading,
	estampede,
	dropstart,
	drop,
	phase1hurt,
	duel,
	deformed,
	grabdash,
	grabthrow,
	wait,
	flamethrower,
	machinegun,
	bazooka,
	crate,
	noisecrusher,
	droptrap,
	skateboardnoise,
	noiseballooncrash,
	swinging,
	stomp,
	ending, // reused by obj_mainmenu
	backtohub,
	johnghost,
	spaceshuttle,
	animation,
	pizzaheadjump,
	fightball,
	secretenter,
	teleport,
	KO,
	camera_followtarget,
	
	// john cash
	UNKNOWN_1, // 300
	UNKNOWN_2, // 301
	UNKNOWN_3, // 302
	UNKNOWN_4, // 303, used by obj_stickhat
	UNKNOWN_5, // 304
	
	// noise
	machcancelstart,
	machcancel,
	
	// sugary
	cotton = 500,
	cottondrill,
	cottonroll,
	fling,
	twirl,
	frothstuck,
	rupertnormal,
	rupertslide,
	rupertjump, 
	rupertstick,
	
	// pto
	debugfly = 600,
	frozen,
}

#endregion
#region struct (for ingame use)

globalvar states;
states = {
	normal : 0,
	revolver : 1,
	dynamite : 2,
	boots : 3,
	grabbed : 4,
	tumble : 5,
	finishingblow : 6,
	ejected : 7,
	transition : 8,
	fireass : 9,
	firemouth : 10,
	mort : 11,
	mortjump : 12,
	mortattack : 13,
	morthook : 14,
	hook : 15,
	ghost : 16,
	ghostpossess : 17,
	titlescreen : 18,
	hookshot : 19,
	tacklecharge : 20,
	cheeseball : 21,
	cheeseballclimbwall : 22,
	slap : 23,
	cheesepep : 24,
	cheesepepstick : 25,
	cheesepepjump : 26,
	cheesepepfling : 27,
	cheesepeplaunch : 28,
	cheesepepstickside : 29,
	cheesepepstickup : 30,
	rideweenie : 31,
	motorcycle : 32,
	boxxedpep : 33,
	boxxedpepspin : 34,
	boxxedpepjump : 35,
	pistolaim : 36,
	climbwall : 37,
	knightpepslopes : 38,
	portal : 39,
	secondjump : 40,
	chainsawbump : 41,
	handstandjump : 42,
	lungeattack : 43,
	lungegrab : 44,
	dashtumble : 45,
	gottreasure : 46,
	knightpep : 47,
	knightpepattack : 48,
	knightpepbump : 49,
	meteorpep : 50,
	bombpep : 51,
	bombgrab : 52,
	bombpepside : 53,
	bombpepup : 54,
	grabbing : 55,
	chainsawpogo : 56,
	shotgunjump : 57,
	pogo : 58,
	stunned : 59,
	highjump : 60,
	chainsaw : 61,
	facestomp : 62,
	mach4 : 63,
	timesup : 64,
	machroll : 65,
	shotgun : 66,
	shotguncrouch : 67,
	shotguncrouchjump : 68,
	shotgunshoot : 69,
	shotgundash : 70,
	shotgunfreefall : 71,
	pistol : 72,
	machfreefall : 73,
	throwing : 74,
	slam : 75,
	superslam : 76,
	skateboard : 77,
	grind : 78,
	grab : 79,
	punch : 80,
	backkick : 81,
	uppunch : 82,
	shoulder : 83,
	backbreaker : 84,
	graffiti : 85,
	bossdefeat : 86,
	pizzathrow : 87,
	bossintro : 88,
	dead : 89,
	keyget : 90,
	tackle : 91,
	jump : 92,
	ladder : 93,
	slipnslide : 94,
	comingoutdoor : 95,
	smirk : 96,
	Sjump : 97,
	victory : 98,
	Sjumpprep : 99,
	crouch : 100,
	crouchjump : 101,
	crouchslide : 102,
	mach1 : 103,
	mach2 : 104,
	machslide : 105,
	bump : 106,
	hurt : 107,
	freefall : 108,
	hang : 109,
	turning : 110, // doesnt exist
	freefallland : 111,
	door : 112,
	barrel : 113,
	barreljump : 114,
	barrelclimbwall : 115,
	barrelslide : 116,
	current : 117,
	boulder : 118,
	taxi : 119,
	runonball : 120,
	mach3 : 121,
	freefallprep : 122,
	Sjumpland : 123,
	faceplant : 124,
	rage : 125,
	idle : 126,
	bounce : 127,
	charge : 128,
	pizzagoblinthrow : 129,
	turn : 130,
	hitceiling : 131, // doesnt exist
	hitwall : 132, // doesnt exist
	groundpoundland : 133,
	walk : 134,
	fall : 135,
	land : 136,
	hit : 137,
	stun : 138,
	recovery : 139, // doesnt exist
	stomped : 140, // doesnt exist
	chase : 141,
	spawnenemy : 142,
	arena : 143,
	arenaintro : 144,
	arenaround : 145,
	actor : 146,
	parry : 147,
	golf : 148,
	float : 149,
	tube : 150,
	policetaxi : 152,
	shoulderbash : 153,
	pummel : 154,
	staggered : 155,
	thrown : 156,
	supershoulderbash : 157,
	superattackstart : 158,
	superattackcharge : 159,
	superattack : 160,
	shoulderturn : 161,
	fistmatch : 162,
	fistmatchend : 163,
	groundpunchstart : 164,
	slipbanan : 165,
	millionpunch : 166,
	skateboardturn : 167,
	bombkick : 168,
	bombpogo : 169,
	jetpackstart : 170,
	jetpack : 171,
	jetpackcancel : 172,
	jetpackspin : 173,
	shield : 174,
	helicopterhat : 175,
	panicjump : 176,
	smokebombstart : 177,
	smokebombcrawl : 178,
	springshoes : 179,
	cardboard : 180,
	cardboardend : 181,
	mockery : 182,
	bombdelete : 183,
	rocket : 184,
	rocketslide : 185,
	gotoplayer : 186,
	trickjump : 187,
	totem : 188,
	underground : 189,
	ridecow : 190,
	ratmount : 191,
	ratmountjump : 192,
	ratmountattack : 193,
	ratmountspit : 194,
	ratmountclimbwall : 195,
	ratmounthurt : 196,
	ratmountgroundpound : 197,
	ratmountbounce : 198,
	ratmountballoon : 200,
	ratmounttumble : 201,
	ratmountgrind : 202,
	ratmounttrickjump : 203,
	ratmountskid : 204,
	ratgrabbed : 205,
	blockstance : 206,
	balloon : 207,
	debugstate : 208,
	trashjumpprep : 209,
	trashjump : 210,
	trashroll : 211,
	stringfling : 212,
	stringjump : 213,
	stringfall : 214,
	noisejetpack : 215,
	spiderweb : 216,
	robotidle : 217,
	robotintro : 218,
	robotroaming : 219,
	robotchase : 220,
	robotinvestigate : 221,
	robotseeking : 222,
	flushidle : 223,
	flushtransition : 224,
	animatronic : 225,
	pizzaface_moustache : 226,
	pizzaface_mouth : 227,
	pizzaface_eyes : 228,
	pizzaface_nose : 229,
	pizzaface_ram : 230,
	pizzaface_phase2transition : 231,
	pizzahead_look : 232,
	pizzahead_fishing : 233,
	pizzahead_bombrun : 235,
	pizzahead_npcthrow : 236,
	pizzahead_portraitthrow : 237,
	pizzahead_enguarde : 238,
	pizzahead_sexypicture : 239,
	pizzahead_pullinglevel : 240,
	pizzahead_eat : 241,
	pizzahead_surprisebox : 242,
	pizzahead_spinningrun : 243,
	pizzahead_spinningkick : 244,
	pizzahead_spinningpunch : 245,
	pizzahead_groundpunch : 246,
	pizzahead_bigkick : 247,
	pizzahead_slamhead : 248,
	pizzahead_slamhead2 : 249,
	tv_whitenoise : 250,
	tv_expression : 251,
	playersuperattack : 252,
	jetpackjump : 254,
	bee : 257,
	bee_chase : 258,
	ratmountpunch : 259,
	ratmountcrouch : 260,
	ratmountladder : 261,
	supergrab : 262,
	magnet : 264,
	antigrav : 265,
	secret : 266,
	contemplate : 267,
	mini : 268,
	reloading : 269,
	estampede : 270,
	dropstart : 271,
	drop : 272,
	phase1hurt : 273,
	duel : 274,
	deformed : 275,
	grabdash : 276,
	grabthrow : 277,
	wait : 278,
	flamethrower : 279,
	machinegun : 280,
	bazooka : 281,
	crate : 282,
	noisecrusher : 283,
	droptrap : 284,
	skateboardnoise : 285,
	noiseballooncrash : 286,
	swinging : 287,
	stomp : 288,
	ending : 289,
	backtohub : 290,
	johnghost : 291,
	spaceshuttle : 292,
	animation : 293,
	pizzaheadjump : 294,
	fightball : 295,
	secretenter : 296,
	teleport : 297,
	KO : 298,
	camera_followtarget : 299,
	
	// john cash
	UNKNOWN_1 : 300, // 300
	UNKNOWN_2 : 301, // 301
	UNKNOWN_3 : 302, // 302
	UNKNOWN_4 : 303, // 303, used by obj_stickhat
	UNKNOWN_5 : 304, // 304
	
	// noise
	machcancelstart : 305,
	machcancel : 306,
	
	// sugary
	cotton : 500,
	cottondrill : 501,
	cottonroll : 502,
	fling : 503,
	twirl : 504,
	frothstuck : 505,
	rupertnormal : 506,
	rupertslide : 507,
	rupertjump : 508,
	rupertstick : 509,
	
	// pto
	debugfly : 600,
	frozen : 601,
}

#endregion